#pragma once


#define COMMON_WEIGHT 100
#define UNCOMMON_WEIGHT 50
#define RARE_WEIGHT 30
#define EPIC_WEIGHT 15
#define LEGENDARY_WEIGHT 5
#define MYTHIC_WEIGHT 1

#define ATTACK_SPEED_WEIGHT 10
#define SPEED_WEIGHT 10
#define PENETRATION_WEIGHT 10
#define DAMAGE_WEIGHT 10

#define COMMON_MODIFIER 1.0f
#define UNCOMMON_MODIFIER 1.05f
#define RARE_MODIFIER 1.1f
#define EPIC_MODIFIER 1.2f
#define LEGENDARY_MODIFIER 1.25f
#define MYTHIC_MODIFIER 1.5f